swagger: '2.0'
info:
  description: | 
    The Wazuh API is an open source RESTful API that allows for interaction with the Wazuh manager from a web browser, command line tool like cURL or any script or program that can make web requests. The Wazuh Kibana app relies on this heavily and Wazuh’s goal is to accommodate complete remote management of the Wazuh infrastructure via the Wazuh Kibana app. Use the API to easily perform everyday actions like adding an agent, restarting the manager(s) or agent(s) or looking up syscheck details.
  version: 3.8.0
  title: Wazuh API
  license:
    name: GPL 2.0
    url: 'https://github.com/wazuh/wazuh/blob/master/LICENSE'
schemes:
  - https
  - http
tags:
- name: agents
  description: 'Agents management related operations'
paths:
  /agents:
    get:
      tags:
      - agents
      summary: 'Get all agents'
      description: 'Returns a list with the available agents.'
      operationId: getAllAgents
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/pretty'
        - $ref: '#/parameters/wait_for_complete'
        - in: query
          name: offset
          description: First element to return in the collection
          type: integer
          format: int32
        - in: query
          name: limit
          description: Maximum number of elements to return
          type: integer
          format: int32
        - in: query
          name: select
          description: Select which fields to return (separated by comma)
          type: array
          items:
            type: string
        # It'd be more appropriate to be an array of strings, and separate the ascending or descending order in another param
        - in: query
          name: sort
          description: |
            Sorts the collection by a field or fields (separated by comma). Use +/- at the beginning to list in ascending or descending order.
          type: string
        - in: query
          name: search
          description: Looks for elements with the specified string
          type: string
        - $ref: '#/parameters/statusParam'
        - in: query
          name: q
          description: Query to filter results by. For example q=&quot;status=Active&quot;
          type: string
        - $ref: '#/parameters/olderThanParam'
        - in: query
          name: os.platform
          description: Filters by OS platform.
          type: string
        - in: query
          name: os.version
          description: Filters by OS version.
          type: string
        - in: query
          name: os.name
          description: Filters by OS name.
          type: string
        - in: query
          name: manager
          description: Filters by manager hostname to which agents are connected.
          type: string
        - in: query
          name: version
          description: Filters by agents version.
          type: string
        - in: query
          name: group
          description: Filters by group of agents.
          type: string
        - in: query
          name: node_name
          description: Filters by node name.
          type: string
        - in: query
          name: name
          description: Filters by agent name.
          type: string
        - in: query
          name: ip
          description: Filters by agent IP
          type: string

      responses:
        '200':
          description: 'List of agents or error description'
          schema:
            allOf:
            - $ref: '#/definitions/ApiResponse'
            - type: object
              properties:
                data:
                  allOf:
                    - $ref: '#/definitions/ListMetadata'
                    - type: object
                      properties:
                        items:
                          type: array
                          items:
                            $ref: '#/definitions/Agent'
            example:
              error: 0
              data:
                totalItems: 7
                items:
                - status: Active
                  configSum: ab73af41699f13fdd81903b5f23d8d00
                  group:
                  - default
                  name: agent1
                  mergedSum: f1a9e24e02ba4cc5ea80a9d3feb3bb9a
                  ip: 192.168.185.7
                  manager: manager
                  node_name: node02
                  dateAdd: '2018-10-11 09:38:47'
                  version: Wazuh v3.8.0
                  lastKeepAlive: '2018-10-11 13:58:08'
                  os:
                    major: '16'
                    name: Ubuntu
                    uname: Linux |ubuntu |4.4.0-135-generic |#161-Ubuntu SMP Mon Aug 27 10:45:01
                      UTC 2018 |x86_64
                    platform: ubuntu
                    version: 16.04.5 LTS
                    codename: Xenial Xerus
                    arch: x86_64
                    minor: '04'
                  id: '001'
                - status: Active
                  name: manager
                  ip: 127.0.0.1
                  manager: manager
                  node_name: node01
                  dateAdd: '2018-10-11 09:37:23'
                  version: Wazuh v3.8.0
                  lastKeepAlive: '9999-12-31 23:59:59'
                  os:
                    major: '18'
                    name: Ubuntu
                    uname: Linux |manager |4.15.0-36-generic |#39-Ubuntu SMP Mon Sep 24 16:19:09
                      UTC 2018 |x86_64
                    platform: ubuntu
                    version: 18.04.1 LTS
                    codename: Bionic Beaver
                    arch: x86_64
                    minor: '04'
                  id: '000'
                - status: Never connected
                  dateAdd: '2018-10-11 13:58:23'
                  name: NewHost_2
                  ip: 10.0.10.10
                  id: '123'
                  node_name: unknown
                - status: Never connected
                  dateAdd: '2018-10-11 13:58:22'
                  name: NewHost
                  ip: 10.0.0.9
                  id: '007'
                  node_name: unknown
                - status: Never connected
                  dateAdd: '2018-10-11 13:58:10'
                  group:
                  - default
                  name: server001
                  ip: 10.0.0.62
                  id: '002'
                  node_name: unknown

    delete:
      tags:
      - agents
      summary: Delete agents
      description: |
        Removes agents, using a list of them or a criterion based on the status or time of the last connection. The Wazuh API must be restarted after removing an agent.
      operationId: deleteAgents
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/pretty'
        - $ref: '#/parameters/wait_for_complete'
        - in: query
          name: ids
          description: Array of agent ID’s
          type: array
          items:
            type: string
        - in: query
          name: purge
          description: Delete an agent from the key store
          type: boolean
        - $ref: '#/parameters/statusParam'
        - $ref: '#/parameters/olderThanParam'

      responses:
        '200':
          description: Delete agents
          schema:
            allOf:
            - $ref: '#/definitions/ApiResponse'
            - type: object
              properties:
                data:
                  $ref: '#/definitions/AgentDeleted'
            example:
              error: 0
              data:
                msg: All selected agents were removed
                older_than: 10s
                affected_agents:
                - '003'
                - '005'
                total_affected_agents: 2

  /agents/restart:
    put:
      tags:
      - agents
      summary: 'Restarts all agents'
      operationId: restart_all_agents
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/wait_for_complete'
      responses:
        '200':
          description: Agents restarted
          schema:
            allOf:
            - $ref: '#/definitions/ApiResponse'
            example:
              data: "Restarting all agents"
              error: 0


parameters:
  olderThanParam:
    in: query
    name: older_than
    description: |
      Filters out disconnected agents for longer than specified. Time in seconds, ‘[n_days]d’, ‘[n_hours]h’, ‘[n_minutes]m’ or ‘[n_seconds]s’. For never connected agents, uses the register date.
    type: string
  statusParam:
    in: query
    name: status
    description: Filters by agent status. Use commas to enter multiple statuses.
    type: array
    items:
      type: string
      enum:
      - active
      - pending
      - neverconnected
      - disconnected
  pretty:
    in: query
    name: pretty
    description: |
      Show results in human-readable format
    type: boolean
  wait_for_complete:
    in: query
    name: wait_for_complete
    description: |
      Disable timeout response
    type: boolean


definitions:

## Common models
  ApiResponse:
    type: object
    required:
    - error
    properties:
      error:
        type: integer
        format: int32
      message:
        type: string
  
  ListMetadata:
    type: object
    properties:
      totalItems:
        type: integer
        format: int32

## Agents models

  Agent:
    type: object
    properties:
      status:
        $ref: '#/definitions/AgentStatus'
      configSum:
        type: string
      group:
        type: array
        items:
          type: string
      name:
        type: string
      mergedSum:
        type: string
      ip:
        type: string
      manager:
        type: string
      node_name:
        type: string
      dateAdd:
        type: string
      version:
        type: string
      lastKeepAlive:
        type: string
      os:
        type: object
        properties:
          major:
            type: string
          name:
            type: string
          uname:
            type: string
          platform:
            type: string
          version:
            type: string
          codename:
            type: string
          arch:
            type: string
          minor:
            type: string
      id:
        type: string


  AgentDeleted:
    type: object
    properties:
      msg:
        type: string
      older_than:
        type: string
      affected_agents:
        type: array
        items:
          type: string
      failed_ids:
        type: array
        items:
          type: string
      total_affected_agents:
        type: integer
        format: int32
  
  AgentStatus:
    type: string
    enum:
    - active
    - pending
    - neverconnected
    - disconnected
  

externalDocs:
  description: Find more about Wazuh API usage
  url: 'https://documentation.wazuh.com/current/user-manual/api/index.html'

