name: Vulnerability Scanner - Generate database

on:
  workflow_dispatch:
  pull_request:
  # Pull request events
    types: [synchronize, opened, reopened, ready_for_review]
  # Path filtering
    paths:
      - ".github/workflows/vulnerability-scanner-generate-database.yml"
      - "src/shared_modules/router/**"
      - "src/shared_modules/content_manager/**"
      - "src/shared_modules/indexer_connector/**"
      - "src/wazuh_modules/vulnerability_scanner/**"
      - "src/wazuh_modules/http-request/**"

jobs:
  vulnerability-scanner-modules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Project dependencies
        uses: ./.github/actions/vulnerability_scanner_deps

      ########################
      # Compilation          #
      ########################

      # Router
      - name: Router - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/router

      # Indexer connector
      - name: Indexer connector - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/indexer_connector

      # Content manager
      - name: Content manager - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/shared_modules/content_manager

      # Vulnerability scanner
      - name: Vulnerability scanner - Compilation and test
        uses: ./.github/actions/compile_and_test
        with:
          path: src/wazuh_modules/vulnerability_scanner

  vulnerability-scanner-generate-content:
    needs: vulnerability-scanner-modules
    runs-on: ubuntu-latest

    steps:
      - name: Vulnerability scanner - Run vd_scanner_testtool
        run: |
          ls -lh src/wazuh_modules/vulnerability_scanner
          
          ls -lh src/wazuh_modules/vulnerability_scanner/build
          
          ./src/wazuh_modules/vulnerability_scanner/build/testtool/scanner/vd_scanner_testtool -c wazuh_modules/vulnerability_scanner/testtool/scanner/config.json -t wazuh_modules/vulnerability_scanner/indexer/template/legacy-template.json -d
               
          rm -rf queue/indexer
          rm -rf queue/sockets
          rm -rf queue/router
          
          tar -cJf vd.tar.xz queue
        shell: bash

  vulnerability-scanner-upload-to-s3:
    needs: vulnerability-scanner-generate-content
    runs-on: ubuntu-latest

    steps:
      - name: Uploading file
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: './vd.tar.xz'